### ISSUE TITLE
Unreasonably high number of contacts after removing age structure

### ISSUE THREAD

**Issue by florpi** [sbfnk/socialmixr#13]
I am trying to obtain the probability that a person of age class i interacts with a person of age class j, regardless of the country's age structure. Which is given by,
C_ij * N/N_j
where N is the total population of the country, and N_j the number of people aged j.

This is the code I am using to extract this matrix, that should be symmetric,
```
data_pop <- contact_matrix(polymod, countries = "United Kingdom", symmetric=TRUE)
div <- sweep(data_pop$matrix, 2, data_pop$demography$proportion, FUN='/')
```
Sorry if the R code is not correct, I'm a python user. The matrix is indeed symmetric, the problem I have is that the resulting matrix contains values as high as 400 for teenagers. Would hat mean they interact on average 400 times a day with people of their own age?

Thank you in advance for your help :)

**Comment by sbfnk** [comment]
Sorry, I'm not sure what you mean by "regardless of the country's age structure". The equation you state doesn't result in a probability. Do you want the `split` option to `contact_matrix`? See the section "Splitting contact matrices" in the [vignette](https://cran.r-project.org/web/packages/socialmixr/vignettes/introduction.html).

**Comment by florpi** [comment]
Sorry, I wasn't very clear. I don't mean the probability, but the mean number of contacts between two different age groups in a population where all age groups contain the same amount of people. It is sometimes referred to as the intrinsic connectivity matrix (see equation 4 here https://www.biorxiv.org/content/10.1101/343491v1.full.pdf)
