### ISSUE TITLE
weighting

### ISSUE THREAD

**Issue by sbfnk** [sbfnk/socialmixr#16]
The current implementation of weighting seems wrong. Participants (and contacts) get weighted according to their weight columns, whereas the weights should be assigned to give certain *target* weights. E.g., in the case of day of the week weighting participants who complete diaries for weekdays get a weight 5 and those who complete diaries for weekends get a weight 2, whereas the weights should be such that the ratio of the sums of all weights of weekend surveys and the sum of all weights of weekday surveys is 2/5.

**Comment by sbfnk** [comment]
relevant lines in code are
https://github.com/sbfnk/socialmixr/blob/90329c7fe237ccf85addaaefb6264a53dfa73b2e/R/contact_matrix.r#L405

up to

https://github.com/sbfnk/socialmixr/blob/90329c7fe237ccf85addaaefb6264a53dfa73b2e/R/contact_matrix.r#L436

**Comment by vikkytom** [comment]
Does this affects "weights = c()" or it affects only "weight.dayofweek"?

**Comment by sbfnk** [comment]
Both.

**Comment by sbfnk** [comment]
Fixed in #19
