### ISSUE TITLE
Country issue for van Hoek et al. survey

### ISSUE THREAD

**Issue by mariabnd** [sbfnk/socialmixr#2]
I wanted to examine both the POLYMOD UK data and the additional UK survey available from van Hoek et al. listed in get_survey. However `contact_matrix(survey = get_survey(2))` yields the error 
```
Error in if (all(nchar(as.character(x$participants[[country.column]])) ==  : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In countrycode(get(country.column), "iso2c", "country.name") :
  Some values were not matched unambiguously: UK
```
This seems to be due to values in ```get_survey(2)$participants$country``` being empty (vs. e.g. "France" for get_survey(8)) as `survey_countries(get_survey(2))` gives the same error message. There also seems to be a variable called X in participants which solely consists of NAs for survey ID 2 in `list_surveys`.

I have attempted adjusting the values manually but `contact_matrix` doesn't like my adjusted version of the data. Might you happen to know what needs to be done to `get_survey(2)` such that I can run `contact_matrix` on it?

R is version 3.5.0 and socialmixr is version 0.1.3

**Comment by sbfnk** [comment]
This should be fixed now in the development version (which can be installed with `install_github`) and make it into the next release.
